#! /usr/bin/env python
# -*- coding: utf-8 -*-
# fixme: 同時押し対応
import sys
def lowercase(num):
    if   num == 0x04: sys.stdout.write("a")
    elif num == 0x05: sys.stdout.write("b")
    elif num == 0x06: sys.stdout.write("c")
    elif num == 0x07: sys.stdout.write("d")
    elif num == 0x08: sys.stdout.write("e")
    elif num == 0x09: sys.stdout.write("f")
    elif num == 0x0a: sys.stdout.write("g")
    elif num == 0x0b: sys.stdout.write("h")
    elif num == 0x0c: sys.stdout.write("i")
    elif num == 0x0d: sys.stdout.write("j")
    elif num == 0x0e: sys.stdout.write("k")
    elif num == 0x0f: sys.stdout.write("l")
    elif num == 0x10: sys.stdout.write("m")
    elif num == 0x11: sys.stdout.write("n")
    elif num == 0x12: sys.stdout.write("o")
    elif num == 0x13: sys.stdout.write("p")
    elif num == 0x14: sys.stdout.write("q")
    elif num == 0x15: sys.stdout.write("r")
    elif num == 0x16: sys.stdout.write("s")
    elif num == 0x17: sys.stdout.write("t")
    elif num == 0x18: sys.stdout.write("u")
    elif num == 0x19: sys.stdout.write("v")
    elif num == 0x1a: sys.stdout.write("w")
    elif num == 0x1b: sys.stdout.write("x")
    elif num == 0x1c: sys.stdout.write("y")
    elif num == 0x1d: sys.stdout.write("z")
    elif num == 0x1e: sys.stdout.write("1")
    elif num == 0x1f: sys.stdout.write("2")
    elif num == 0x20: sys.stdout.write("3")
    elif num == 0x21: sys.stdout.write("4")
    elif num == 0x22: sys.stdout.write("5")
    elif num == 0x23: sys.stdout.write("6")
    elif num == 0x24: sys.stdout.write("7")
    elif num == 0x25: sys.stdout.write("8")
    elif num == 0x26: sys.stdout.write("9")
    elif num == 0x27: sys.stdout.write("0")
    elif num == 0x28: sys.stdout.write("\n")
    elif num == 0x29: sys.stdout.write("<Esc>")
    elif num == 0x2a: sys.stdout.write("<Del>")
    elif num == 0x2b: sys.stdout.write("	")
    elif num == 0x2c: sys.stdout.write(" ")
    elif num == 0x2d: sys.stdout.write("-")
    elif num == 0x2e: sys.stdout.write("=")
    elif num == 0x2f: sys.stdout.write("[")
    elif num == 0x30: sys.stdout.write("]")
    elif num == 0x31: sys.stdout.write("\\")
    elif num == 0x33: sys.stdout.write(";")
    elif num == 0x34: sys.stdout.write("'")
    elif num == 0x35: sys.stdout.write("`")
    elif num == 0x36: sys.stdout.write(",")
    elif num == 0x37: sys.stdout.write(".")
    elif num == 0x38: sys.stdout.write("/")
    elif num == 0x00: sys.stdout.write("")
    else: print "<%02x>" % num,

def uppercase(num):
    if   num == 0x04: sys.stdout.write("A")
    elif num == 0x05: sys.stdout.write("B")
    elif num == 0x06: sys.stdout.write("C")
    elif num == 0x07: sys.stdout.write("D")
    elif num == 0x08: sys.stdout.write("E")
    elif num == 0x09: sys.stdout.write("F")
    elif num == 0x0a: sys.stdout.write("G")
    elif num == 0x0b: sys.stdout.write("H")
    elif num == 0x0c: sys.stdout.write("I")
    elif num == 0x0d: sys.stdout.write("J")
    elif num == 0x0e: sys.stdout.write("K")
    elif num == 0x0f: sys.stdout.write("L")
    elif num == 0x10: sys.stdout.write("M")
    elif num == 0x11: sys.stdout.write("N")
    elif num == 0x12: sys.stdout.write("O")
    elif num == 0x13: sys.stdout.write("P")
    elif num == 0x14: sys.stdout.write("Q")
    elif num == 0x15: sys.stdout.write("R")
    elif num == 0x16: sys.stdout.write("S")
    elif num == 0x17: sys.stdout.write("T")
    elif num == 0x18: sys.stdout.write("U")
    elif num == 0x19: sys.stdout.write("V")
    elif num == 0x1a: sys.stdout.write("W")
    elif num == 0x1b: sys.stdout.write("X")
    elif num == 0x1c: sys.stdout.write("Y")
    elif num == 0x1d: sys.stdout.write("Z")
    elif num == 0x1e: sys.stdout.write("!")
    elif num == 0x1f: sys.stdout.write("@")
    elif num == 0x20: sys.stdout.write("#")
    elif num == 0x21: sys.stdout.write("$")
    elif num == 0x22: sys.stdout.write("%")
    elif num == 0x23: sys.stdout.write("^")
    elif num == 0x24: sys.stdout.write("&")
    elif num == 0x25: sys.stdout.write("*")
    elif num == 0x26: sys.stdout.write("(")
    elif num == 0x27: sys.stdout.write(")")
    elif num == 0x28: sys.stdout.write("\n")
    elif num == 0x29: sys.stdout.write("<Esc>")
    elif num == 0x2a: sys.stdout.write("<Del>")
    elif num == 0x2b: sys.stdout.write("	")
    elif num == 0x2c: sys.stdout.write(" ")
    elif num == 0x2d: sys.stdout.write("-")
    elif num == 0x2e: sys.stdout.write("=")
    elif num == 0x2f: sys.stdout.write("[")
    elif num == 0x30: sys.stdout.write("]")
    elif num == 0x31: sys.stdout.write("\\")
    elif num == 0x33: sys.stdout.write(";")
    elif num == 0x34: sys.stdout.write("'")
    elif num == 0x35: sys.stdout.write("`")
    elif num == 0x36: sys.stdout.write(",")
    elif num == 0x37: sys.stdout.write(".")
    elif num == 0x38: sys.stdout.write("/")
    elif num == 0x00: sys.stdout.write("")
    else: print "Shift-<%02x>" % num,

def ctrlcase(num):
    if   num == 0x04: sys.stdout.write("<C-A>")
    elif num == 0x05: sys.stdout.write("<C-B>")
    elif num == 0x06: sys.stdout.write("<C-C>")
    elif num == 0x07: sys.stdout.write("<C-D>")
    elif num == 0x08: sys.stdout.write("<C-E>")
    elif num == 0x09: sys.stdout.write("<C-F>")
    elif num == 0x0a: sys.stdout.write("<C-G>")
    elif num == 0x0b: sys.stdout.write("<C-H>")
    elif num == 0x0c: sys.stdout.write("<C-I>")
    elif num == 0x0d: sys.stdout.write("<C-J>")
    elif num == 0x0e: sys.stdout.write("<C-K>")
    elif num == 0x0f: sys.stdout.write("<C-L>")
    elif num == 0x10: sys.stdout.write("<C-M>")
    elif num == 0x11: sys.stdout.write("<C-N>")
    elif num == 0x12: sys.stdout.write("<C-O>")
    elif num == 0x13: sys.stdout.write("<C-P>")
    elif num == 0x14: sys.stdout.write("<C-Q>")
    elif num == 0x15: sys.stdout.write("<C-R>")
    elif num == 0x16: sys.stdout.write("<C-S>")
    elif num == 0x17: sys.stdout.write("<C-T>")
    elif num == 0x18: sys.stdout.write("<C-U>")
    elif num == 0x19: sys.stdout.write("<C-V>")
    elif num == 0x1a: sys.stdout.write("<C-W>")
    elif num == 0x1b: sys.stdout.write("<C-X>")
    elif num == 0x1c: sys.stdout.write("<C-Y>")
    elif num == 0x1d: sys.stdout.write("<C-Z>")
    elif num == 0x1e: sys.stdout.write("<C-!>")
    elif num == 0x1f: sys.stdout.write("<C-@>")
    elif num == 0x20: sys.stdout.write("<C-#>")
    elif num == 0x21: sys.stdout.write("<C-$>")
    elif num == 0x22: sys.stdout.write("<C-%>")
    elif num == 0x23: sys.stdout.write("<C-^>")
    elif num == 0x24: sys.stdout.write("<C-&>")
    elif num == 0x25: sys.stdout.write("<C-*>")
    elif num == 0x26: sys.stdout.write("<C-(>")
    elif num == 0x27: sys.stdout.write("<C-)>")
    elif num == 0x28: sys.stdout.write("<C-\n")
    elif num == 0x29: sys.stdout.write("<C-Esc>")
    elif num == 0x2a: sys.stdout.write("<C-Del>")
    elif num == 0x2b: sys.stdout.write("<C-	>")
    elif num == 0x2c: sys.stdout.write("<C- >")
    elif num == 0x2d: sys.stdout.write("<C-->")
    elif num == 0x2e: sys.stdout.write("<C-=>")
    elif num == 0x2f: sys.stdout.write("<C-[>")
    elif num == 0x30: sys.stdout.write("<C-]>")
    elif num == 0x31: sys.stdout.write("<C-\\>")
    elif num == 0x33: sys.stdout.write("<C-;>")
    elif num == 0x34: sys.stdout.write("<C-'>")
    elif num == 0x35: sys.stdout.write("<C-`>")
    elif num == 0x36: sys.stdout.write("<C-,>")
    elif num == 0x37: sys.stdout.write("<C-.>")
    elif num == 0x38: sys.stdout.write("<C-/>")
    elif num == 0x00: sys.stdout.write("<C->")
    else: print "<C-%02x>" % num,

def altcase(num):
    if   num == 0x04: sys.stdout.write("<Alt-A>")
    elif num == 0x05: sys.stdout.write("<Alt-B>")
    elif num == 0x06: sys.stdout.write("<Alt-C>")
    elif num == 0x07: sys.stdout.write("<Alt-D>")
    elif num == 0x08: sys.stdout.write("<Alt-E>")
    elif num == 0x09: sys.stdout.write("<Alt-F>")
    elif num == 0x0a: sys.stdout.write("<Alt-G>")
    elif num == 0x0b: sys.stdout.write("<Alt-H>")
    elif num == 0x0c: sys.stdout.write("<Alt-I>")
    elif num == 0x0d: sys.stdout.write("<Alt-J>")
    elif num == 0x0e: sys.stdout.write("<Alt-K>")
    elif num == 0x0f: sys.stdout.write("<Alt-L>")
    elif num == 0x10: sys.stdout.write("<Alt-M>")
    elif num == 0x11: sys.stdout.write("<Alt-N>")
    elif num == 0x12: sys.stdout.write("<Alt-O>")
    elif num == 0x13: sys.stdout.write("<Alt-P>")
    elif num == 0x14: sys.stdout.write("<Alt-Q>")
    elif num == 0x15: sys.stdout.write("<Alt-R>")
    elif num == 0x16: sys.stdout.write("<Alt-S>")
    elif num == 0x17: sys.stdout.write("<Alt-T>")
    elif num == 0x18: sys.stdout.write("<Alt-U>")
    elif num == 0x19: sys.stdout.write("<Alt-V>")
    elif num == 0x1a: sys.stdout.write("<Alt-W>")
    elif num == 0x1b: sys.stdout.write("<Alt-X>")
    elif num == 0x1c: sys.stdout.write("<Alt-Y>")
    elif num == 0x1d: sys.stdout.write("<Alt-Z>")
    elif num == 0x1e: sys.stdout.write("<Alt-!>")
    elif num == 0x1f: sys.stdout.write("<Alt-@>")
    elif num == 0x20: sys.stdout.write("<Alt-#>")
    elif num == 0x21: sys.stdout.write("<Alt-$>")
    elif num == 0x22: sys.stdout.write("<Alt-%>")
    elif num == 0x23: sys.stdout.write("<Alt-^>")
    elif num == 0x24: sys.stdout.write("<Alt-&>")
    elif num == 0x25: sys.stdout.write("<Alt-*>")
    elif num == 0x26: sys.stdout.write("<Alt-(>")
    elif num == 0x27: sys.stdout.write("<Alt-)>")
    elif num == 0x28: sys.stdout.write("<Alt-\n>")
    elif num == 0x29: sys.stdout.write("<Alt-Esc>")
    elif num == 0x2a: sys.stdout.write("<Alt-Del>")
    elif num == 0x2b: sys.stdout.write("<Alt-	>")
    elif num == 0x2c: sys.stdout.write("<Alt- >")
    elif num == 0x2d: sys.stdout.write("<Alt-->")
    elif num == 0x2e: sys.stdout.write("<Alt-=>")
    elif num == 0x2f: sys.stdout.write("<Alt-[>")
    elif num == 0x30: sys.stdout.write("<Alt-]>")
    elif num == 0x31: sys.stdout.write("<Alt-\\>")
    elif num == 0x33: sys.stdout.write("<Alt-;>")
    elif num == 0x34: sys.stdout.write("<Alt-'>")
    elif num == 0x35: sys.stdout.write("<Alt-`>")
    elif num == 0x36: sys.stdout.write("<Alt-,>")
    elif num == 0x37: sys.stdout.write("<Alt-.>")
    elif num == 0x38: sys.stdout.write("<Alt-/>")
    elif num == 0x00: sys.stdout.write("<Alt->")
    else: print "<Alt-%02x>" % num,

def commandcase(num):
    if   num == 0x04: sys.stdout.write("<Command-A>")
    elif num == 0x05: sys.stdout.write("<Command-B>")
    elif num == 0x06: sys.stdout.write("<Command-C>")
    elif num == 0x07: sys.stdout.write("<Command-D>")
    elif num == 0x08: sys.stdout.write("<Command-E>")
    elif num == 0x09: sys.stdout.write("<Command-F>")
    elif num == 0x0a: sys.stdout.write("<Command-G>")
    elif num == 0x0b: sys.stdout.write("<Command-H>")
    elif num == 0x0c: sys.stdout.write("<Command-I>")
    elif num == 0x0d: sys.stdout.write("<Command-J>")
    elif num == 0x0e: sys.stdout.write("<Command-K>")
    elif num == 0x0f: sys.stdout.write("<Command-L>")
    elif num == 0x10: sys.stdout.write("<Command-M>")
    elif num == 0x11: sys.stdout.write("<Command-N>")
    elif num == 0x12: sys.stdout.write("<Command-O>")
    elif num == 0x13: sys.stdout.write("<Command-P>")
    elif num == 0x14: sys.stdout.write("<Command-Q>")
    elif num == 0x15: sys.stdout.write("<Command-R>")
    elif num == 0x16: sys.stdout.write("<Command-S>")
    elif num == 0x17: sys.stdout.write("<Command-T>")
    elif num == 0x18: sys.stdout.write("<Command-U>")
    elif num == 0x19: sys.stdout.write("<Command-V>")
    elif num == 0x1a: sys.stdout.write("<Command-W>")
    elif num == 0x1b: sys.stdout.write("<Command-X>")
    elif num == 0x1c: sys.stdout.write("<Command-Y>")
    elif num == 0x1d: sys.stdout.write("<Command-Z>")
    elif num == 0x1e: sys.stdout.write("<Command-!>")
    elif num == 0x1f: sys.stdout.write("<Command-@>")
    elif num == 0x20: sys.stdout.write("<Command-#>")
    elif num == 0x21: sys.stdout.write("<Command-$>")
    elif num == 0x22: sys.stdout.write("<Command-%>")
    elif num == 0x23: sys.stdout.write("<Command-^>")
    elif num == 0x24: sys.stdout.write("<Command-&>")
    elif num == 0x25: sys.stdout.write("<Command-*>")
    elif num == 0x26: sys.stdout.write("<Command-(>")
    elif num == 0x27: sys.stdout.write("<Command-)>")
    elif num == 0x28: sys.stdout.write("<Command-\n>")
    elif num == 0x29: sys.stdout.write("<Command-Esc>")
    elif num == 0x2a: sys.stdout.write("<Command-Del>")
    elif num == 0x2b: sys.stdout.write("<Command-	>")
    elif num == 0x2c: sys.stdout.write("<Command- >")
    elif num == 0x2d: sys.stdout.write("<Command-->")
    elif num == 0x2e: sys.stdout.write("<Command-=>")
    elif num == 0x2f: sys.stdout.write("<Command-[>")
    elif num == 0x30: sys.stdout.write("<Command-]>")
    elif num == 0x31: sys.stdout.write("<Command-\\>")
    elif num == 0x33: sys.stdout.write("<Command-;>")
    elif num == 0x34: sys.stdout.write("<Command-'>")
    elif num == 0x35: sys.stdout.write("<Command-`>")
    elif num == 0x36: sys.stdout.write("<Command-,>")
    elif num == 0x37: sys.stdout.write("<Command-.>")
    elif num == 0x38: sys.stdout.write("<Command-/>")
    elif num == 0x00: sys.stdout.write("<Command->")
    else: print "<Command-%02x>" % num,

def main():
    argvs = sys.argv
    argc = len(argvs)
    if argc < 2:
        print "usage: python ./bin <data_file>"
        exit()
    f = open(argvs[1])
    rawdata = f.read()
    f.close()

    lines = rawdata.split('\n')
    for line in lines:
        num_line = []
        output = []
        line = line.split(':')
        num = (int(line[2], 16))
        if (int(line[0], 16)) == 0x01 or (int(line[0], 16)) == 0x10: ctrlcase(num) # 0x01: Ctrl
        elif (int(line[0], 16)) == 0x02 or (int(line[0], 16)) == 0x20: uppercase(num) # 0x02: shift
        elif (int(line[0], 16)) == 0x04 or (int(line[0], 16)) == 0x40: altcase(num) # 0x04: Alt/Option
        elif (int(line[0], 16)) == 0x08 or (int(line[0], 16)) == 0x80: commandcase(num) # 0x08: command(Mac)
        elif (int(line[0], 16)) == 0x00: lowercase(num)
        else: print "<unknown:%s>" % line[0],

if __name__ == "__main__":
    main()
